[package]
name = "discord-ng-japanese"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
serenity = "0.12.2"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
